### ISSUE TITLE
Description for owner input is confusing

### ISSUE THREAD

**Issue by martincostello** [actions/create-github-app-token#116]
I'm looking to migrate to this action from [peter-murray/workflow-application-token-action](https://github.com/peter-murray/workflow-application-token-action) (currently waiting on #111 for feature parity) and I found the documentation for the `owner` input confusing:

https://github.com/actions/create-github-app-token/blob/f2acddfb5195534d487896a656232b016a682f3c/action.yml#L22-L24

To me, the documentation implies that this should be the owner of the GitHub app itself, whereas if you trace through the code it's _actually_ the owner for which the GitHub app is _installed_ (i.e. the place you want to give the app access to).

https://github.com/actions/create-github-app-token/blob/f2acddfb5195534d487896a656232b016a682f3c/lib/main.js#L112-L129

**Comment by gr2m** [comment]
> the owner for which the GitHub app is _installed_

that is correct. Sorry for the confusion. We should definitely update the input description. Pull request welcome!
