### ISSUE TITLE
post-action warning on revoke failure in case token already expired

### ISSUE THREAD

**Issue by danra** [actions/create-github-app-token#140]
I'm seeing the following warning in the post job cleanup step:
```
Post job cleanup.
Warning: Token revocation failed: Bad credentials - https://docs.github.com/rest
```

Probably because the token was already invalidated, because the job took more than 1h to run (see https://github.com/actions/create-github-app-token/issues/121).

No issue here other than there shouldn't be any warning in this case.

**Comment by gr2m** [comment]
We do already check for expiration time, maybe we got it implemented wrong though?
https://github.com/actions/create-github-app-token/blob/c8f55efbd427e7465d6da1106e7979bc8aaee856/lib/post.js#L24-L28

**Comment by dboriichuk** [comment]
I just want to +1 to this issue.
It happens in jobs, which runs for several hours.
