### ISSUE TITLE
Invalid Releases

### ISSUE THREAD

**Issue by dsanders11** [actions/create-github-app-token#31]
This action has multiple tagged versions, but `dist/` has never been updated, so all of the versions are identical.

The action template repos have a workflow to detect this situation: https://github.com/actions/javascript-action/blob/main/.github/workflows/check-dist.yml

**Comment by gr2m** [comment]
we have automation in place to update the `dist/` file but recently changed it, looks like the new automation is not working, I'll look into it

**Comment by parkerbxyz** [comment]
Fixed in #33.

**Comment by parkerbxyz** [comment]
Thanks for noticing and reporting this, @dsanders11! :sparkles:
