### ISSUE TITLE
Add integration tests as end-to-end tests fail for pull requests coming from forks

### ISSUE THREAD

**Issue by gr2m** [actions/create-github-app-token#32]
we considered using `pull_request_target` in order to give access to repository secrets, but decided against it. See https://github.com/actions/create-github-app-token/pull/17#issuecomment-1688591600 for more context.

We want to continue running the end-to-end tests as we have them anyway, but we want to add integration tests with mocked requests which won't require credentials and can also be run locally with `npm test`

We use Node's built-in `fetch`. Here are some relevant guides for testing/mocking

- https://undici.nodejs.org/#/docs/best-practices/writing-tests
- https://undici.nodejs.org/#/docs/best-practices/mocking-request

**Comment by parkerbxyz** [comment]
Oops! This was linked to the wrong pull request.
