### ISSUE TITLE
Support organization-scope installation token

### ISSUE THREAD

**Issue by kmaehashi** [actions/create-github-app-token#44]
Thank you for making a great Action! We've been relying on third-party actions or [raw github-script](https://github.com/kmaehashi/github-app-token-workflow/blob/main/.github/workflows/github-app-token.yml) for a long time, so it's great to see the official solution finally!

One request I'd like to make is to support retrieving [organization-scoped installation token](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-organization-installation-for-the-authenticated-app). One of the example use-cases is to automate the GitHub Project (V2), as illustrated in the GitHub's official documentation (which currently uses `tibdex/github-app-token`):

https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions

GitHub Project (V2) is a resource tied to organizations, so repository-scope access should be essentially unnecessary for the App.

**Comment by gr2m** [comment]
can we close this issue in favor of https://github.com/actions/create-github-app-token/issues/4?

**Comment by kmaehashi** [comment]
Thanks, sounds good to close!
