### ISSUE TITLE
Proposal: Use dashes (instead of underscores) in input names

### ISSUE THREAD

**Issue by smockle** [actions/create-github-app-token#57]
From @gr2m in https://github.com/actions/create-github-app-token/pull/54#discussion_r1344571256:
> I think we should use dashes for our arguments, it seems to be the convention for `actions/*` actions, e.g. see https://github.com/actions/checkout/

Notably, changing the input names affects the translated environment variable names[^1]:
- An input named `my_var` is translated to `INPUTS_MY_VAR`.
- An input named `my-var` is translated to `INPUTS_MY-VAR`.

So, we may want a plan for backwards-compatibility, or we may want to ship this in a major version bump.

[^1]: cf. [“Metadata syntax for GitHub Actions > Example: Specifying inputs”](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs)

**Comment by gr2m** [comment]
The way I would go about it is to release a feature version that

1. supports both input types
2. Logs a deprecation warning for the old notation
3. Add a test for deprecations

Then once we release a new breaking version we can always look into the deprecations test file and remove them. It's a pattern that worked well for me in the past in several projects

**Comment by smockle** [comment]
Opened https://github.com/actions/create-github-app-token/pull/59 to support this.
