### ISSUE TITLE
404 when attempting to get a token for an organisation scoped app installation

### ISSUE THREAD

**Issue by ctcampbell** [actions/create-github-app-token#76]
I have an app installation set up on an organisation, having followed the docs on this repo. It appears the lookup is being done against the `/users/...` endpoint which doesn't seem correct for an organisation?

```
Run actions/create-github-app-token@v1
  with:
    app-id: ***
    private-key: ***
    owner: pre-quantum-research
repositories not set, creating token for all repositories for given owner "pre-quantum-research"
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:2890:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:10071:22) {
  status: 404,
  response: {
    url: 'https://api.github.com/users/pre-quantum-research/installation',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 06 Nov 2023 16:52:05 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=3[15](https://github.com/pre-quantum-research/pqc-data/actions/runs/6773907521/job/18409828846#step:2:16)36000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '4820:56A0:49A3574:96BB6B3:6549[19](https://github.com/pre-quantum-research/pqc-data/actions/runs/6773907521/job/18409828846#step:2:21)B5',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/apps/apps#get-a-user-installation-for-the-authenticated-app'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/users/pre-quantum-research/installation',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/create-github-app-token',
      authorization: 'bearer [REDACTED]'
    }
  }
}
```

**Comment by gr2m** [comment]
> It appears the lookup is being done against the `/users/...` endpoint which doesn't seem correct for an organisation?

We do both. There is no unified REST API endpoint, so we try the org lookup first, and then do the user lookup:
https://github.com/actions/create-github-app-token/blob/bb368d6a108e1f8f77914270decfd728d4a44138/lib/main.js#L95-L112

I agree the error we through could be more helpful though. We should make clear that an installation was not found for `pre-quantum-research` and do not share the details about the final failed request to the `/users/{org}/installation` endpoint.

In your case, it looks like the app is not installed on @pre-quantum-research. If you register a GitHub app, you still need to install it, even if it's an app private to your organization.

**Comment by ctcampbell** [comment]
> In your case, it looks like the app is not installed on [@pre-quantum-research](https://github.com/pre-quantum-research). If you register a GitHub app, you still need to install it, even if it's an app private to your organization.

You are absolutely correct, silly me 😅

**Comment by gr2m** [comment]
No worries, I've been there countless times myself 😁

**Comment by chandapukiran** [comment]
Hi, i have similar issue. In my case; i already have app installed on the repository but still get the error. 

`7s
Warning: Input 'private_key' has been deprecated with message: 'private_key' is deprecated and will be removed in a future version. Use 'private-key' instead.
Warning: Input 'app_id' has been deprecated with message: 'app_id' is deprecated and will be removed in a future version. Use 'app-id' instead.
Run actions/create-github-app-token@v[1](https://github.com/yoyoIgnitor/renovate-configure/actions/runs/6953777267/job/18919446722#step:3:1)
owner and repositories not set, creating token for the current repository ("renovate-configure")
Failed to create token for "renovate-configure" (attempt 1): Not Found
Failed to create token for "renovate-configure" (attempt [2](https://github.com/yoyoIgnitor/renovate-configure/actions/runs/6953777267/job/18919446722#step:3:2)): Not Found
Failed to create token for "renovate-configure" (attempt [3](https://github.com/yoyoIgnitor/renovate-configure/actions/runs/6953777267/job/18919446722#step:3:3)): Not Found
Failed to create token for "renovate-configure" (attempt 4): Not Found
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:2890:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getTokenFromRepository (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:10435:20)
    at async RetryOperation._fn (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:10318:24) {
Error: Not Found
  status: 404,
  response: {
    url: 'https://api.github.com/repos/yoyoIgnitor/renovate-configure/installation',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Wed, 22 Nov 2023 06:3[7](https://github.com/yoyoIgnitor/renovate-configure/actions/runs/6953777267/job/18919446722#step:3:8):54 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-2[8](https://github.com/yoyoIgnitor/renovate-configure/actions/runs/6953777267/job/18919446722#step:3:9)',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '1842:862A:7278E0:ECB[9](https://github.com/yoyoIgnitor/renovate-configure/actions/runs/6953777267/job/18919446722#step:3:10)F9:655DA1BE',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/yoyoIgnitor/renovate-configure/installation',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/create-github-app-token',
      authorization: 'bearer [REDACTED]'
    }
  },
  attemptNumber: 4,
  retriesLeft: 0
}`

**Comment by chandapukiran** [comment]
<img width="1207" alt="image" src="https://github.com/actions/create-github-app-token/assets/122605789/4de58d13-38be-470e-993a-e01a560f86f8">

**Comment by ViliusS** [comment]
I have the same issue, however mine GitHub App is create and installed at organization level.

```
Run actions/create-github-app-token@v1
  with:
    app-id: XXXXXX
    private-key: ***
    owner: rivile-org
repositories not set, creating token for all repositories for given owner "rivile-org"
Failed to create token for "rivile-org" (attempt 1): Integration not found
Failed to create token for "rivile-org" (attempt [2](https://github.com/rivile-org/erp-rivile_shared/actions/runs/7529563294/job/20494509083#step:2:2)): Integration not found
Failed to create token for "rivile-org" (attempt [3](https://github.com/rivile-org/erp-rivile_shared/actions/runs/7529563294/job/20494509083#step:2:3)): Integration not found
Failed to create token for "rivile-org" (attempt [4](https://github.com/rivile-org/erp-rivile_shared/actions/runs/7529563294/job/20494509083#step:2:4)): Integration not found
RequestError [HttpError]: Integration not found
    at /home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:2900:2[5](https://github.com/rivile-org/erp-rivile_shared/actions/runs/7529563294/job/20494509083#step:2:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Integration not found
    at async hook (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:9902:22)
    at async getTokenFromOwner (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:1042[6](https://github.com/rivile-org/erp-rivile_shared/actions/runs/7529563294/job/20494509083#step:2:7):20)
    at async RetryOperation._fn (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:10329:24) {
  status: 404,
  response: {
    url: 'https://api.github.com/users/rivile-org/installation',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-[8](https://github.com/rivile-org/erp-rivile_shared/actions/runs/7529563294/job/20494509083#step:2:9)',
      date: 'Mon, 15 Jan 2024 13:43:01 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '41C4:3B0B:13F126D:2[9](https://github.com/rivile-org/erp-rivile_shared/actions/runs/7529563294/job/20494509083#step:2:10)6E6D3:65A53665',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Integration not found',
      documentation_url: 'https://docs.github.com/rest'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/users/rivile-org/installation',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/create-github-app-token',
      authorization: 'bearer [REDACTED]'
    },
    request: { hook: [Function: bound hook] AsyncFunction }
  },
  attemptNumber: 4,
  retriesLeft: 0
}
```

Any ideas where to look further?
