### ISSUE TITLE
AWS system manager( Parameter store )

### ISSUE THREAD

**Issue by ankushkatiyar** [actions/create-github-app-token#97]
Hello team, 
I'm using create-github-app-token action to generate token and i'm able to generate token successfully. But i want to store generated token from create-github-app-token action in AWS system manager( Parameter store ) and from parameter store i want to access GitHub REST API.

When i perform the step that i mentioned above i can see this output

```json
{
    "message": "Bad credentials",
    "documentation_url": "https://docs.github.com/rest"
}
```

It seems stored token in AWS SSM is not correct.
When i use GitHub REST API in GitHub actions and use the generated token from  create-github-app-token action, it works.
Can you help me in this why i'm not to able to use the stored token in GitHub REST APIs in different client's like Postman

**Comment by gr2m** [comment]
Note that the token is only valid for 1h. Is it possible that the token expired by the time you are trying to use it?

**Comment by gr2m** [comment]
> I hope generated token from create-github-app-token action is not encrypted

No it's not

I don't think this is a problem with the `create-github-app-token` action. If you have more questions please comment, but I'm going to close this issue as there is nothing actionable for us to do, and we want to reserve issues for actionable items
